In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = load_iris(return_X_y=True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
import numpy as np # StandardScaler manually

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[ 1.20949876,  0.04450676,  0.89824305,  1.15398615],
       [ 0.49569621,  0.48957437,  1.23667057,  1.68051975],
       [ 2.0422684 , -0.17802704,  1.57509809,  1.15398615],
       [ 2.16123549, -0.17802704,  1.29307516,  1.41725295],
       [ 1.56640003,  1.15717578,  1.29307516,  1.68051975],
       [ 1.20949876,  0.26704057,  1.06745681,  1.41725295],
       [ 1.80433421, -0.62309465,  1.29307516,  0.89071934],
       [ 0.25776203, -0.17802704,  0.44700635,  0.23255234],
       [ 0.13879494,  0.71210817,  0.39060177,  0.49581914],
       [-1.52674433,  0.71210817, -1.35794043, -1.21541507],
       [-0.57500761,  0.71210817, -1.30153585, -1.08378167],
       [-0.81294179,  0.71210817, -1.35794043, -1.34704847],
       [-0.33707342, -0.17802704,  0.16498342,  0.10091894],
       [ 0.97156458,  0.04450676,  0.50341094,  0.36418574],
       [-1.64571143, -1.73576368, -1.41434502, -1.21541507],
       [-0.45604052, -1.51322987, -0.06063493, -0.29398126],
       [ 0.97156458, -1.

In [9]:
X_train_scaled

array([[ 1.20949876,  0.04450676,  0.89824305,  1.15398615],
       [ 0.49569621,  0.48957437,  1.23667057,  1.68051975],
       [ 2.0422684 , -0.17802704,  1.57509809,  1.15398615],
       [ 2.16123549, -0.17802704,  1.29307516,  1.41725295],
       [ 1.56640003,  1.15717578,  1.29307516,  1.68051975],
       [ 1.20949876,  0.26704057,  1.06745681,  1.41725295],
       [ 1.80433421, -0.62309465,  1.29307516,  0.89071934],
       [ 0.25776203, -0.17802704,  0.44700635,  0.23255234],
       [ 0.13879494,  0.71210817,  0.39060177,  0.49581914],
       [-1.52674433,  0.71210817, -1.35794043, -1.21541507],
       [-0.57500761,  0.71210817, -1.30153585, -1.08378167],
       [-0.81294179,  0.71210817, -1.35794043, -1.34704847],
       [-0.33707342, -0.17802704,  0.16498342,  0.10091894],
       [ 0.97156458,  0.04450676,  0.50341094,  0.36418574],
       [-1.64571143, -1.73576368, -1.41434502, -1.21541507],
       [-0.45604052, -1.51322987, -0.06063493, -0.29398126],
       [ 0.97156458, -1.

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
X_train_scaled

array([[0.72222222, 0.45833333, 0.77192982, 0.83333333],
       [0.55555556, 0.54166667, 0.87719298, 1.        ],
       [0.91666667, 0.41666667, 0.98245614, 0.83333333],
       [0.94444444, 0.41666667, 0.89473684, 0.91666667],
       [0.80555556, 0.66666667, 0.89473684, 1.        ],
       [0.72222222, 0.5       , 0.8245614 , 0.91666667],
       [0.86111111, 0.33333333, 0.89473684, 0.75      ],
       [0.5       , 0.41666667, 0.63157895, 0.54166667],
       [0.47222222, 0.58333333, 0.61403509, 0.625     ],
       [0.08333333, 0.58333333, 0.07017544, 0.08333333],
       [0.30555556, 0.58333333, 0.0877193 , 0.125     ],
       [0.25      , 0.58333333, 0.07017544, 0.04166667],
       [0.36111111, 0.41666667, 0.54385965, 0.5       ],
       [0.66666667, 0.45833333, 0.64912281, 0.58333333],
       [0.05555556, 0.125     , 0.05263158, 0.08333333],
       [0.33333333, 0.16666667, 0.47368421, 0.375     ],
       [0.66666667, 0.20833333, 0.84210526, 0.70833333],
       [0.5       , 0.41666667,

In [12]:
import numpy as np # MinMaxScaler manually

X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)

array([[0.72222222, 0.45833333, 0.77192982, 0.83333333],
       [0.55555556, 0.54166667, 0.87719298, 1.        ],
       [0.91666667, 0.41666667, 0.98245614, 0.83333333],
       [0.94444444, 0.41666667, 0.89473684, 0.91666667],
       [0.80555556, 0.66666667, 0.89473684, 1.        ],
       [0.72222222, 0.5       , 0.8245614 , 0.91666667],
       [0.86111111, 0.33333333, 0.89473684, 0.75      ],
       [0.5       , 0.41666667, 0.63157895, 0.54166667],
       [0.47222222, 0.58333333, 0.61403509, 0.625     ],
       [0.08333333, 0.58333333, 0.07017544, 0.08333333],
       [0.30555556, 0.58333333, 0.0877193 , 0.125     ],
       [0.25      , 0.58333333, 0.07017544, 0.04166667],
       [0.36111111, 0.41666667, 0.54385965, 0.5       ],
       [0.66666667, 0.45833333, 0.64912281, 0.58333333],
       [0.05555556, 0.125     , 0.05263158, 0.08333333],
       [0.33333333, 0.16666667, 0.47368421, 0.375     ],
       [0.66666667, 0.20833333, 0.84210526, 0.70833333],
       [0.5       , 0.41666667,

In [13]:
# Feature Encoding
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [14]:
data = fetch_openml('car', as_frame=True).frame

C:\Users\abdul\Desktop\Python\Scikit Learn\.venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)


In [18]:
data

,buying,maint,doors,persons,lug_boot,safety,binaryClass
0,vhigh,vhigh,2,2,small,low,P
1,vhigh,vhigh,2,2,small,med,P
2,vhigh,vhigh,2,2,small,high,P
3,vhigh,vhigh,2,2,med,low,P
4,vhigh,vhigh,2,2,med,med,P
...,...,...,...,...,...,...,...
1723,low,low,5more,more,med,med,N
1724,low,low,5more,more,med,high,N
1725,low,low,5more,more,big,low,P
1726,low,low,5more,more,big,med,N


In [19]:
columns_to_encode = ['lug_boot', 'safety']
encoder = OrdinalEncoder(
    categories = [
        ['small', 'med', 'big'],
        ['low', 'med', 'high'],
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [20]:
data

,buying,maint,doors,persons,lug_boot,safety,binaryClass
0,vhigh,vhigh,2,2,0.0,0.0,P
1,vhigh,vhigh,2,2,0.0,1.0,P
2,vhigh,vhigh,2,2,0.0,2.0,P
3,vhigh,vhigh,2,2,1.0,0.0,P
4,vhigh,vhigh,2,2,1.0,1.0,P
...,...,...,...,...,...,...,...
1723,low,low,5more,more,1.0,1.0,N
1724,low,low,5more,more,1.0,2.0,N
1725,low,low,5more,more,2.0,0.0,P
1726,low,low,5more,more,2.0,1.0,N


In [21]:
encoder.inverse_transform(data[columns_to_encode]) 

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

In [22]:
# OneHotEncoder 
data = fetch_openml('adult', as_frame=True).frame

C:\Users\abdul\Desktop\Python\Scikit Learn\.venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)


In [23]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K


In [24]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [27]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoded_values = encoder.fit_transform(data[['occupation', 'race']])
new_cols = encoder.get_feature_names_out(['occupation', 'race'])

In [28]:
encoded_values

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(48842, 20))

In [29]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [ ]:
df_encoded = pd.DataFrame(encoded_values, columns=new_cols, index=data.index)

data_final = pd.concat(
    [data.drop(columns['occupation', 'race']), df_encoded],
    axis=1
)